server:
  applicationConnectors:
    - type: http
      port: 9080
  adminConnectors:
    - type: http
      port: 9081
logging:
  level: INFO
  loggers:
    com.akashrungta: DEBUG
swagger:
  resourcePackage: "com.akashrungta.game.mancala.api"
